const mealRecipes = [
  {
    name: 'Biryani',
    ingredients: [
      '2 cups of basmati rice',
      '1 pound of chicken (cut into pieces)',
      '1 large onion, sliced',
      '2 tablespoons of biryani masala',
      '1 cup of plain yogurt',
      '2 tablespoons of ghee or clarified butter',
      '2 cloves of garlic, minced',
      '1 piece of ginger, grated',
      '1 cinnamon stick',
      '2 cardamom pods',
      '2 cloves',
      'Fresh coriander for garnish',
    ],
    steps: [
      'Rinse the rice in cold water and soak for 30 minutes.',
      'Heat ghee in a large pot, add cinnamon, cardamom, and cloves, and sauté until fragrant.',
      'Add onions and cook until golden brown.',
      'Add garlic, ginger, and chicken pieces, and sauté until the chicken is browned.',
      'Add biryani masala and mix well.',
      'Add yogurt and let it simmer until the chicken is cooked.',
      'Drain the rice and layer it over the chicken mixture.',
      'Cover the pot and cook on low heat for 20-25 minutes until the rice is cooked through.',
      'Garnish with fresh coriander and serve hot.',
    ],
  },
  {
    name: 'Burger',
    ingredients: [
      '1 pound of ground beef',
      '1 egg',
      '1/4 cup of bread crumbs',
      '1 teaspoon of salt',
      '1/2 teaspoon of black pepper',
      '4 burger buns',
      'Lettuce leaves',
      'Tomato slices',
      'Cheese slices (optional)',
      'Ketchup and mustard for garnish',
    ],
    steps: [
      'In a bowl, combine ground beef, egg, bread crumbs, salt, and pepper.',
      'Form the mixture into 4 burger patties.',
      'Heat a skillet or grill over medium-high heat.',
      'Cook the burger patties for 3-4 minutes on each side or until they are done to your liking.',
      'Toast the burger buns if desired.',
      'Assemble the burgers with lettuce, tomato, cheese (optional), ketchup, and mustard.',
      'Serve hot and enjoy!',
    ],
  },
  {
    name: 'Butter Chicken',
    ingredients: [
      '1 pound of chicken (cut into pieces)',
      '1 cup of tomato puree',
      '1/2 cup of heavy cream',
      '2 tablespoons of butter',
      '2 cloves of garlic, minced',
      '1 piece of ginger, grated',
      '1 teaspoon of garam masala',
      '1/2 teaspoon of turmeric',
      '1/2 teaspoon of chili powder',
      'Salt to taste',
      'Fresh coriander for garnish',
    ],
    steps: [
      'Heat butter in a large skillet over medium heat.',
      'Add garlic, ginger, and chicken pieces, and sauté until the chicken is browned.',
      'Add tomato puree, turmeric, chili powder, and garam masala, and cook for 10-15 minutes.',
      'Add heavy cream and mix well.',
      'Simmer on low heat for another 10-15 minutes or until the chicken is cooked through.',
      'Garnish with fresh coriander and serve with rice or naan bread.',
    ],
  },
  {
    name: 'Dessert',
    ingredients: [
      '2 cups of all-purpose flour',
      '1 cup of sugar',
      '1/2 cup of unsalted butter',
      '2 eggs',
      '1 teaspoon of vanilla extract',
      '1/2 teaspoon of baking powder',
      '1/2 teaspoon of salt',
      '1/2 cup of milk',
    ],
    steps: [
      'Preheat the oven to 350 degrees Fahrenheit.',
      'In a large bowl, combine flour, sugar, baking powder, and salt.',
      'In a separate bowl, whisk together eggs, butter, vanilla extract, and milk.',
      'Add the wet ingredients to the dry ingredients and mix until combined.',
      'Pour the batter into a greased cake pan and bake for 25-30 minutes or until a toothpick inserted comes out clean.',
      'Allow the cake to cool, then serve with your favorite icing or toppings.',
    ],
  },
  {
    name: 'Dosa',
    ingredients: [
      '1 cup of rice',
      '1/2 cup of urad dal (black lentils)',
      '1 teaspoon of fenugreek seeds',
      'Salt to taste',
      '2 tablespoons of vegetable oil',
    ],
    steps: [
      'Rinse rice and urad dal and soak them with fenugreek seeds for 6-8 hours.',
      'Grind the soaked rice and urad dal to make a smooth batter.',
      'Add salt and allow the batter to ferment overnight.',
      'Heat a non-stick pan or dosa griddle, pour a ladleful of batter, and spread it in a circular motion.',
      'Add some oil around the edges and let it cook until crispy.',
      'Fold the dosa and serve hot with chutney and sambar.',
    ],
  },
  {
    name: 'Idly',
    ingredients: [
      '1 cup of rice',
      '1/2 cup of urad dal (black lentils)',
      '1 teaspoon of fenugreek seeds',
      'Salt to taste',
      '2 tablespoons of vegetable oil',
    ],
    steps: [
      'Rinse rice and urad dal and soak them with fenugreek seeds for 6-8 hours.',
      'Grind the soaked rice and urad dal to make a smooth batter.',
      'Add salt and allow the batter to ferment overnight.',
      'Pour the batter into idly molds and steam for 10-15 minutes or until the idlies are soft and fluffy.',
      'Serve with chutney and sambar.',
    ],
  },
  {
    name: 'Pasta',
    ingredients: [
      '200 grams of pasta (such as penne or fusilli)',
      '1 bell pepper, sliced',
      '1 zucchini, sliced',
      '1 cup of cherry tomatoes',
      '2 cloves of garlic, minced',
      '1/4 cup of olive oil',
      'Salt and pepper to taste',
      'Fresh basil leaves for garnish',
    ],
    steps: [
      'Cook the pasta according to package instructions and drain.',
      'Heat olive oil in a large skillet over medium heat.',
      'Add garlic, bell pepper, and zucchini, and sauté until tender.',
      'Add cherry tomatoes and cook for another 3-4 minutes.',
      'Add the cooked pasta to the skillet and toss to combine.',
      'Season with salt and pepper.',
      'Garnish with fresh basil leaves and serve hot.',
    ],
  },
  {
    name: 'Pizza',
    ingredients: [
      '1 pizza dough',
      '1/2 cup of pizza sauce',
      '1 cup of mozzarella cheese, shredded',
      'Fresh basil leaves for garnish',
      '1 tablespoon of olive oil',
    ],
    steps: [
      'Preheat the oven to 425 degrees Fahrenheit.',
      'Roll out the pizza dough and place it on a baking sheet.',
      'Spread pizza sauce evenly over the dough.',
      'Sprinkle mozzarella cheese on top of the sauce.',
      'Drizzle olive oil over the pizza.',
      'Bake in the oven for 12-15 minutes or until the crust is golden brown and the cheese is melted.',
      'Garnish with fresh basil leaves before serving.',
    ],
  },
  {
    name: 'Rice',
    ingredients: ['2 cups of white rice', '4 cups of water', 'Salt to taste'],
    steps: [
      'Rinse rice in cold water until the water runs clear.',
      'In a pot, bring water to a boil.',
      'Add rice and salt to the boiling water.',
      'Reduce heat, cover, and simmer for 18-20 minutes or until rice is tender.',
      'Fluff rice with a fork and serve.',
    ],
  },
  {
    name: 'Samosa',
    ingredients: [
      '2 cups of all-purpose flour',
      '1/2 cup of ghee or butter',
      '1 teaspoon of salt',
      '1/2 cup of water',
      '2 boiled potatoes',
      '1/2 cup of peas',
      '1 onion, diced',
      '1 teaspoon of cumin seeds',
      '1 teaspoon of garam masala',
      '1 green chili, minced',
      '1 tablespoon of vegetable oil',
    ],
    steps: [
      'In a bowl, mix flour, salt, and ghee or butter.',
      'Gradually add water to form a firm dough.',
      'Cover the dough and let it rest for 30 minutes.',
      'For the filling, heat oil in a skillet, add cumin seeds, and let them crackle.',
      'Add onions, green chili, boiled potatoes, and peas, and cook for 10 minutes.',
      'Add garam masala and mix well.',
      'Roll out the dough and cut into circles.',
      'Fold the circles into cones and fill with the potato mixture.',
      'Seal the edges and fry in hot oil until golden brown.',
      'Serve hot with chutney or sauce.',
    ],
  },
];
export default mealRecipes;
